export const routeHeaders: any = {
  '/procurement': 'Procurement',
  '/default': 'Default',
};

export const orderData = [
  {
    id: 1,
    orderId: '3533 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: true,
    isAnchored: false,
    info: true,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: '#ff451a',
    },
  },
  {
    id: 2,
    orderId: '3453 - 04435',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: false,
    isAnchored: true,
    info: false,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: 'green',
    },
  },
  {
    id: 3,
    orderId: '13421 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: true,
    isAnchored: false,
    info: false,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: '#ff451a',
    },
  },
  {
    id: 4,
    orderId: '4545 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: true,
    isAnchored: true,
    info: false,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: '#ff9f1d',
    },
  },
  {
    id: 5,
    orderId: '5745 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: true,
    isAnchored: false,
    info: true,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: 'green',
    },
  },
  {
    id: 6,
    orderId: '7687 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: false,
    isAnchored: false,
    info: true,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: 'green',
    },
  },
  {
    id: 7,
    orderId: '4675 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: false,
    isAnchored: true,
    info: false,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: 'green',
    },
  },
  {
    id: 8,
    orderId: '3533 - 00233',
    name: 'HOTEL/TECH WORK SQUAD GFR',
    category: 'Service',
    date: new Date(),
    isPinned: true,
    isAnchored: false,
    info: false,
    user: {
      name: 'Hardik Tamore',
      email: 'hardiktamore.ht@gmail.com',
      avatarBg: 'green',
    },
  },
];
